" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'altercation/vim-colors-solarized'
" Plug 'lifepillar/vim-solarized8'
Plug 'tpope/vim-fugitive'
Plug 'pangloss/vim-javascript'
" Plug 'mxw/vim-jsx'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
" Plug 'wikitopian/hardmode'
" Plug 'hashivim/vim-terraform'
" Plug 'leafgarland/typescript-vim'
Plug 'autozimu/LanguageClient-neovim', {'branch': 'next','do': 'bash install.sh',}
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  let g:deoplete#enable_at_startup = 1
  let g:python3_host_prog = '/Users/vinh/.anyenv/envs/pyenv/versions/3.8.3/bin/python'
else
  Plug 'lifepillar/vim-mucomplete'
  "" specific config for mucomplete
  let g:mucomplete#enable_auto_at_startup = 1
  let g:mucomplete#completion_delay = 1
  set completeopt+=menuone
  set completeopt+=noinsert
  set shortmess+=c
endif
call plug#end()
set nocompatible
filetype off
map <C-p> :FZF<CR>
set encoding=utf-8
syntax on
filetype plugin indent on

" Auto complete
set omnifunc=syntaxcomplete#Complete
set completefunc=LanguageClient#complete

set background=dark
" let g:solarized_visibility = "high"
" let g:solarized_contrast = "high"
" colorscheme solarized
" set termguicolors
colorscheme solarized
" let g:solarized_termcolors=256
" set t_Co=256
map <C-n> :NERDTreeFind<CR>
map <C-Left> :tabprevious<CR>
map <C-Left> :tabnext<CR>
set expandtab
set shiftwidth=2
" Old nerdtree auto-close command
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
set laststatus=2
set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

" Search relate
set hlsearch
set incsearch

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Set wild menu. Demo: :spe<tab><tab>
set wildmenu
set wildmode=list:longest,full

" Moving around viewport
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Remap VIM 0 to first non-blank character
map 0 ^

" Linebreak on 500 characters
set lbr
set tw=500

" With a map leader it's possible to do extra key combinations
let mapleader = ","
let g:mapleader = ","

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
" map <leader>t<leader> :tabnext<cr>
map <leader><tab> :tabnext<cr>

" Set copy to system clipboard
map <leader>c "+y
map <leader>p "+p

" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" Enable/Disable line number
nmap <leader>n :set invnumber<CR>

" Set to auto read when a file is changed from the outside
set autoread

" Write with sudo
cmap w!! %!sudo tee > /dev/null %

" Set login shell
" set shell=zsh\ --interactive

" vim markdown plugin
let g:vim_markdown_folding_disabled=1

function! HasPaste()
  if &paste
    return 'PASTE MODE '
  en
    return ''
endfunction

function! CmdLine(str)
    exe "menu Foo.Bar :" . a:str
    emenu Foo.Bar
    unmenu Foo
endfunction

" Vim Hard mode
" autocmd VimEnter,BufNewFile,BufReadPost * silent! call HardMode()
" nnoremap <leader>h <Esc>:call ToggleHardMode()<CR>

" config for vim-markdown
" disable spell-check
let g:markdown_enable_spell_checking = 0

" Transparent background
hi Normal guibg=NONE ctermbg=NONE

let g:LanguageClient_serverCommands = {
    \ 'c': ['/Users/vinh/Programs/clangd_10.0.0/bin/clangd'],
    \ 'cpp': ['/Users/vinh/Programs/clangd_10.0.0/bin/clangd'],
    \ 'python': ['/Users/vinh/Workspace/Personal/python-language-server/bin/pyls'],
    \ }
" set hidden
" let g:LanguageClient_serverCommands = {'typescript': ['tcp://127.0.0.1:2089']}

function LC_maps()
  if has_key(g:LanguageClient_serverCommands, &filetype)
    nnoremap <buffer> <silent> <leader>k :call LanguageClient#textDocument_hover()<cr>
    nnoremap <buffer> <silent> <leader>d :call LanguageClient#textDocument_definition()<CR>
    nnoremap <buffer> <silent> <leader>a :call LanguageClient#textDocument_codeAction()<CR>
  endif
endfunction

autocmd FileType * call LC_maps()
" nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>

" for more information :help completeopt
set completeopt=menuone,noinsert,noselect

lua <<EOF
local opts = { noremap=true, silent=true }
local formattingOptions = { tabSize=2, insertSpaces=true }
local on_attach = function(client, bufnr)
  -- Enable completion triggered by <c-x><c-o>
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  -- See `:help vim.lsp.*` for documentation on any of the below functions
  vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
  vim.api.nvim_buf_set_keymap(bufnr, 'n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
  vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>f', '<cmd>lua vim.lsp.buf.formatting({tabSize=2})<CR>', opts)
end
require('lspconfig')['tsserver'].setup{
  on_attach = on_attach,
  cmd = {"typescript-language-server", "--stdio", "--tsserver-path", "tsserver"},
}
EOF

